name: FPL Daily Team Generation

on:
  schedule:
    - cron:  '0 6 * * *'
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Scrape Understat xG Data
        run: python3 scrape_understat.py

      - name: Run FPL Predictor Script
        run: python3 fpl_play_point_predictor_tp.py

      - name: Run FPL Optimizer Script
        run: python3 fpl_optimizer.py > optimized_squad.txt

      - name: Pull latest main branch
        run: |
          git config user.name "FPL GitHub Action"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Automated FPL data update"
          file_pattern: "fpl_predictions_v2.csv understat_data.csv optimized_squad.txt"
          commit_user_name: "FPL GitHub Action"
          commit_user_email: "actions@github.com"
          push_options: '--force-with-lease'